.TH PHYSLOCK 1 physlock\-VERSION
.SH NAME
physlock \- lock all consoles / virtual terminals
.SH SYNOPSIS
.B physlock
.RB [ \-dhLlmsv ]
.RB [ \-f
.IR FONTFILE ]
.RB [ \-p
.IR MSG ]
.SH DESCRIPTION
physlock is an alternative to vlock, it is equivalent to `vlock \-an'. It is
written because vlock blocks some linux kernel mechanisms like hibernate and
suspend and can therefore only be used with some limitations.
.P
physlock is designed to be lightweight, but highly depends on the kernels ioctl
API.
.P
The behaviour of physlock is completely controlled via command-line arguments,
it does not rely on environment variables.
physlock uses the utmp file to identify the owner of the current session (i.e.
active tty) and prompts for their password to unlock the computer.
.P
Since physlock can display dynamic values on the lock screen (i.e. time of
day, and battery capacity), it will also respond to SIGUSR1 by refreshing
its screen, which is useful after the system resumes from suspend.  (The
screen will update within 30 seconds, even without SIGUSR1.)
.P
physlock will accept the password of the user which owns the VT at
which physlock was invoked.  If no user is logged in on that VT, the
root password will be required.  WARNING:  This means that if physlock
is invoked independently of a login session, perhaps based on timeout,
or by a special key, and there is no password for root, then you may
be locked out of the machine.  Having a root password available is
recommended when using physlock.
.SH OPTIONS
.TP
.B \-b
Show battery capacity.  Currently hardcoded to use
the value of /sys/class/power_supply/BAT0/capacity.
.TP
.B \-c
Allow "shutdown" and "reboot" commands (literally), in addition to
the user password.  No authentication is performed.
.TP
.B \-d
Fork and detach physlock before prompting for authentication. The parent
process returns right after everything is set up, so this option is useful for
use in suspend/hibernate scripts.
.TP
.BI "\-f " FONTFILE
Set the console font using 
.IR FONTFILE .
.B FONTFILE
must be a full pathname, and will be loaded by /usr/bin/setfont.
.TP
.B \-h
Print brief usage information to standard output and exit.
.TP
.B \-l
Only lock console switching and exit.
.TP
.B \-L
Only enable (unlock) console switching and exit. This is useful when a prior
instance of physlock has crashed and leaved the console switching mechanism
locked.
.TP
.B \-m
Mute kernel messages on console while physlock is running.
.TP
.BI "\-p " MSG
Display
.I MSG
when physlock starts.
.TP
.B \-r
Causes physlock to ask for the root password, rather than that of
the logged-in user, every fourth attempt. 
.TP
.B \-s
Disable SysRq mechanism while physlock is running.
.TP
.B \-t
Display date and time.
.TP
.B \-v
Print version information to standard output and exit.
.SH AUTHORS
.TP
Bert Muennich <ber.t at gmx.com>
Battery levels, shutdown/reboot commands and others: Paul Fox 
.SH HOMEPAGE
.TP
http://github.com/muennich/physlock
.SH SEE ALSO
.BR vlock (1)
