#!/bin/bash

timeout=2    # minutes

case $1 in
-r|--refresh)
	# cause a screen refresh.  useful after a suspend/resume
	killall -USR1 vislock
	exit
	;;
esac

# set up a lock, so we only start one copy of vislock at a time
(
	flock -n 9 || exit 1

	me=${0##*/}

	# don't lock the machine if there are no users
	test "$(users)" || exit 0

	# if the system seems to have a battery, display its capacity
	if [ -r /sys/class/power_supply/BAT0/capacity ]
	then
		bopt="-b"
	fi

	# maybe put /etc/issue at top of screen:
	# printf -v msg "%s\n\n\n\n" "$(agetty --show-issue)"
	# or a random fortune:
	# printf -v msg "%s" "$(/usr/games/fortune literature)"

	# or, simply space vislock down to near the middle of the screen
	printf -v msg '\n\n\n\n\n\n\n\n\n\n\n\n\n\n'

	vl=/usr/local/bin/vislock 
	$vl -dmct -o $timeout $bopt -p "$msg" \
		-f /usr/share/consolefonts/Lat15-TerminusBold32x16.psf.gz

) 9<$0
