#!/bin/bash

case $1 in
-r)
	# cause a screen refresh.  useful after a suspend/resume
	killall -USR1 vislock
	exit
	;;
esac

# set up a lock, so we only start one copy of vislock at a time
(
	flock -n 9 || exit 1

	me=${0##*/}

	# don't lock the machine if there are no users
	test "$(users)" || exit 0

	# prefer our modified vislock, but fall back to the system one
	# if ours isn't installed correctly
	myvislock=/usr/local/bin/vislock
	sysvislock=/usr/bin/physlock

	if [ -x $myvislock -a -u $myvislock ]
	then
	    $myvislock -dbct \
		-f /usr/share/consolefonts/Lat15-TerminusBold32x16.psf.gz
	else
	    printf -v positioncursor "\e[14H"
	    $sysvislock -d -p "$positioncursor"
	fi

) 9<$0
