.TH PHYSLOCK 1 vislock\-VERSION
.SH NAME
vislock \- lock all consoles / virtual terminals
.SH SYNOPSIS
.B vislock
.RB [ \-dhLlmsv ]
.RB [ \-f
.IR FONTFILE ]
.RB [ \-p
.IR MSG ]
.SH DESCRIPTION
vislock is a fork of the physlock screen locker, renamed to avoid
confusion with the original, and with the distribution packages named
"physlock".
.P
physlock is an alternative to vlock, it is equivalent to `vlock \-an'. It is
written because vlock blocks some linux kernel mechanisms like hibernate and
suspend and can therefore only be used with some limitations.
.P
vislock adds some features to physlock, mostly driven by personal whim.
.P
The behaviour of vislock is completely controlled via command-line arguments,
it does not rely on environment variables.
vislock uses the utmp file to identify the owner of the current session (i.e.
active tty) and prompts for their password to unlock the computer.
.P
Since vislock can display dynamic values on the lock screen (i.e. time of
day, and battery capacity), it will also respond to SIGUSR1 by refreshing
its screen, which is useful after the system resumes from suspend.  (The
screen will update within 30 seconds, even without SIGUSR1.)
.P
vislock will accept the password for any of the local users whose
names are obtained from logind (or utmp), as well as for users listed
on the command line with -u options.

.SH OPTIONS
.TP
.B \-b
Show battery capacity on lockscreen.  Currently hardcoded to use
the value of /sys/class/power_supply/BAT0/capacity.
.TP
.B \-c
Allow "shutdown" and "reboot" commands (literally), in addition to
the user password.  No authentication is performed.
.TP
.B \-d
Fork and detach vislock before prompting for authentication. The parent
process returns right after everything is set up, so this option is useful for
use in suspend/hibernate scripts.
.TP
.BI "\-f " FONTFILE
Set the console font using 
.IR FONTFILE .
.B FONTFILE
must be a full pathname, and will be loaded by /usr/bin/setfont.
.TP
.B \-h
Print brief usage information to standard output and exit.
.TP
.B \-l
Only lock console switching and exit.
.TP
.B \-L
Only enable (unlock) console switching and exit. This is useful when a prior
instance of vislock has crashed and left the console switching mechanism
locked.
.TP
.B \-m
Mute kernel messages on console while vislock is running.
.TP
.BI "\-p " MSG
Display
.I MSG
when vislock starts.
.TP
.B \-s
Disable SysRq mechanism while vislock is running.
.TP
.B \-t
Display date and time on the lockscreen.
.TP
.BI "\-u " USER
Unlock when USER's password is given.  If given multiple times, 
any of the respective user passwords will cause an unlock.
.TP
.B \-v
Print version information to standard output and exit.
.SH AUTHORS
.TP
Bert Muennich <ber.t at gmx.com> wrote physlock.
Paul Fox (foxharp on github) add support for battery capacity display,
shutdown/reboot commands and more.  (2024)
.SH HOMEPAGE
.TP
http://github.com/muennich/vislock
.SH SEE ALSO
.BR vlock (1)
